### ISSUE TITLE
John Dusaitis's site

### ISSUE THREAD

**Issue by dousaitis** [jackmcdade/five-minute-feedback#12]
Hi Jack!

First of all, thank you for this repo and your helpful advice. I'm waiting for the [Radical Design Course](https://radicaldesigncourse.com/) to get more ideas.

I would like your opinion about my personal website at https://dusaitis.com/. As I love _pixel art_, I tried to make it looks like an arcade game. 

Any feedback is welcome!

Thanks,
John

**Comment by dousaitis** [comment]
@jackmcdade I enhanced the home page with some Animations. 

<img width="960" alt="Screenshot 2020-07-06 at 9 44 49 PM" src="https://user-images.githubusercontent.com/14273133/86628044-f6ecb700-bfd1-11ea-8273-a2b7c73fb99d.png">

Thanks!

**Comment by jackmcdade** [comment]
Nice! What about making them full viewport width? having them appear out of nowhere with a hard edge seems odd.

**Comment by dousaitis** [comment]
Hi @jackmcdade! Thanks for the feedback. I tried to convert the layout to full-screen mode but I couldn't make it looks good. So, I tried something else, to make blurry the right and left side of the screen.

<img width="1274" alt="Animations" src="https://user-images.githubusercontent.com/14273133/87302182-956ca100-c519-11ea-9e97-45830ecf4da5.png">

What about this one?

**Comment by jackmcdade** [comment]
Perfect!


On July 13, 2020 at 8:01:42 AM, John Dusaitis (notifications@github.com)
wrote:

Hi @jackmcdade <https://github.com/jackmcdade>! Thanks for the feedback. I
tried to convert the layout to full-screen mode but I couldn't make it look
good. So, I tryied something else, to make blurry the right and left side
of the screen.

[image: Animations]
<https://user-images.githubusercontent.com/14273133/87302182-956ca100-c519-11ea-9e97-45830ecf4da5.png>

What about this one?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jackmcdade/five-minute-feedback/issues/12#issuecomment-657519232>,
or unsubscribe

**Comment by dousaitis** [comment]
Hi @jackmcdade ,

I did some redesign, so the new version of my blog is this one:

![Screenshot 2020-11-18 at 11 32 37 AM](https://user-images.githubusercontent.com/14273133/99512213-e261f780-2991-11eb-9709-2588e7beefde.png)


Feedback is welcome.

The live version:

https://dusaitis.com/

Thank you :)

**Comment by jackmcdade** [comment]
Here you go @dusaitis! https://youtu.be/VDKgbl-2yPk

**Comment by dousaitis** [comment]
Thank you @jackmcdade for the review!! 😄 

I really appreciate it. I will do the fixes/changes and I will come back to you! 

Regards,
John

**Comment by dousaitis** [comment]
Hi @jackmcdade ,

After, your suggestions I redesigned to [this one](https://dusaitis.com/):

<img width="1410" alt="Screenshot 2020-11-21 at 11 00 06 PM" src="https://user-images.githubusercontent.com/14273133/99887480-727f9580-2c4d-11eb-8f1f-dc94447526f4.png">

Thank you!
John

**Comment by jackmcdade** [comment]
Very nice! 👌
